project:
  type: default
  output-dir: output

metadata-files:
  - data/cv-data.yml

format:
  pdf:
    documentclass: article
    papersize: a4
    margin-left: 1.5cm
    margin-right: 1.5cm
    margin-top: 1.5cm
    margin-bottom: 1.5cm
    fontsize: 10pt
    linestretch: 1.2
    colorlinks: true
    linkcolor: blue
    urlcolor: blue
    toc: false
    embed-resources: true
    pdf-engine: xelatex
    include-in-header:
      text: |
        \usepackage{fontspec}
        \usepackage{xcolor}
        \usepackage{enumitem}
        \usepackage{titlesec}
        \usepackage{fancyhdr}
        \usepackage[most]{tcolorbox}
        
        % Modern font setup
        \setmainfont{TeX Gyre Heros}  % Modern sans-serif font similar to Helvetica
        \setsansfont{TeX Gyre Heros}
        \setmonofont{TeX Gyre Cursor}
        
        % Define modern colors
        \definecolor{primarycolor}{HTML}{2c3e50}
        \definecolor{secondarycolor}{HTML}{3498db}
        \definecolor{accentcolor}{HTML}{e74c3c}
        \definecolor{lightgray}{HTML}{ecf0f1}
        \definecolor{darkgray}{HTML}{34495e}
        
        % Modern section formatting
        \titleformat{\section}
          {\normalfont\Large\bfseries\color{primarycolor}}
          {\thesection}{0.5em}{}
          [\vspace{-0.5em}\color{secondarycolor}\hrule height 1.5pt\vspace{0.5em}]
        
        \titleformat{\subsection}
          {\normalfont\large\bfseries\color{primarycolor}}
          {\thesubsection}{0.5em}{}
        
        \titleformat{\subsubsection}
          {\normalfont\normalsize\bfseries\color{darkgray}}
          {\thesubsubsection}{0.5em}{}
        
        % Adjust spacing
        \titlespacing{\section}{0pt}{8pt}{6pt}
        \titlespacing{\subsection}{0pt}{6pt}{4pt}
        \titlespacing{\subsubsection}{0pt}{4pt}{2pt}
        
        % Modern list styling
        \setlist{noitemsep,topsep=2pt,parsep=2pt,partopsep=0pt,leftmargin=*}
        \setlist[itemize]{label=\textcolor{secondarycolor}{\textbullet}}
        
        % Remove page numbers
        \pagestyle{empty}
        
        % Reduce spacing in title
        \makeatletter
        \renewcommand{\maketitle}{
          \begin{center}
            {\LARGE\bfseries\color{primarycolor}\@title\par}
            \vspace{0.3em}
            {\large\color{darkgray}\@author\par}
            \vspace{0.2em}
            {\color{darkgray}\@date\par}
          \end{center}
          \vspace{0.5em}
        }
        \makeatother

  html:
    theme: 
      - cosmo
      - assets/css/custom.css
    toc: true
    toc-location: left
    toc-depth: 2
    embed-resources: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    fontsize: 1.1em
    linestretch: 1.5
    mainfont: "Source Sans Pro, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, sans-serif"
    monofont: "Source Code Pro, Monaco, Consolas, monospace"

  revealjs:
    theme: [default, assets/css/reveal-custom.css]
    slide-number: true
    chalkboard: false
    embed-resources: true
    width: 1920
    height: 1080
    margin: 0.05
    center: true
    navigationMode: linear
    controlsLayout: bottom-right
    controlsTutorial: false
    hash: true
    history: false
    transition: slide
    transition-speed: default
    background-transition: fade
    fontfamily: "Source Sans Pro"
    
execute:
  echo: false
  warning: false
  message: false

knitr:
  opts_chunk:
    echo: false
    warning: false
    message: false
    comment: ''